"use client";

import { useEffect, useRef, useState, useTransition, type RefObject } from "react";
import { useRouter } from "next/navigation";
import { createMedicationAction, loadChatAction, sendChatAction, type WebChatMessage } from "@/lib/hub/actions";
import styles from "./dashboard.module.css";

type Suggestion = { label?: string; prompt?: string; icon?: string };
const quickPrompts = ["O que voc\u00ea consegue fazer?", "Qual \u00e9 minha pr\u00f3xima dose?", "Quais medicamentos eu tomo hoje?", "Como est\u00e1 minha ades\u00e3o?"];
const intervals = [6, 8, 12, 24] as const;
const colors = [{ value: "blue", label: "Azul", swatch: "#2d73d5" }, { value: "mint", label: "Verde", swatch: "#48a78a" }, { value: "amber", label: "\u00c2mbar", swatch: "#d9963d" }, { value: "coral", label: "Coral", swatch: "#d86f5c" }, { value: "violet", label: "Violeta", swatch: "#8b6cc0" }];

function CapsuleGlyph() {
  return <span className={styles.toolCapsule} aria-hidden="true"><i /><b /><em /></span>;
}
function ChatGlyph({ close = false }: { close?: boolean }) { return close ? <span className={styles.closeGlyph} aria-hidden="true" /> : <span className={styles.chatGlyph} aria-hidden="true"><i /><i /><i /></span>; }
function getSuggestions(message: WebChatMessage): Suggestion[] { const metadata = message.metadata; if (!metadata || typeof metadata !== "object" || Array.isArray(metadata)) return []; const suggestions = (metadata as Record<string, unknown>).suggestions; return Array.isArray(suggestions) ? suggestions.filter((item): item is Suggestion => Boolean(item) && typeof item === "object" && typeof (item as Suggestion).prompt === "string") : []; }
function tone(message: WebChatMessage) { const metadata = message.metadata; if (!metadata || typeof metadata !== "object" || Array.isArray(metadata)) return "default"; const value = (metadata as Record<string, unknown>).feedbackTone; return value === "success" || value === "warning" || value === "danger" ? value : "default"; }

export function AddMedicationButton() {
  return <button className={styles.addMedicationButton} type="button" onClick={() => window.dispatchEvent(new CustomEvent("vitalis:add-medication"))}><span aria-hidden="true">+</span> Adicionar medicamento</button>;
}

function MedicationDrawer({ open, onClose }: { open: boolean; onClose: () => void }) {
  const router = useRouter();
  const [step, setStep] = useState(0); const [name, setName] = useState(""); const [dosage, setDosage] = useState(""); const [firstDoseTime, setFirstDoseTime] = useState("08:00"); const [intervalHours, setIntervalHours] = useState<number>(8); const [durationDays, setDurationDays] = useState<number | null>(null); const [instructions, setInstructions] = useState(""); const [colorToken, setColorToken] = useState("blue"); const [error, setError] = useState(""); const [saving, startSaving] = useTransition();
  useEffect(() => { if (!open) return; const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; document.addEventListener("keydown", onKey); return () => document.removeEventListener("keydown", onKey); }, [open, onClose]);
  if (!open) return null;
  function next() { setError(""); if (step === 0 && (name.trim().length < 2 || name.trim().length > 120 || !dosage.trim())) { setError("Informe o nome e a dosagem do medicamento."); return; } if (step === 1 && !/^([01]\d|2[0-3]):([0-5]\d)$/.test(firstDoseTime)) { setError("Informe um hor\u00e1rio v\u00e1lido."); return; } setStep((value) => Math.min(3, value + 1)); }
  function submit() { setError(""); startSaving(async () => { try { await createMedicationAction({ name, dosage, firstDoseTime, intervalHours, durationDays, instructions, colorToken }); router.refresh(); onClose(); setStep(0); } catch (cause) { setError(cause instanceof Error ? cause.message : "N\u00e3o foi poss\u00edvel salvar o medicamento."); } }); }
  return <div className={styles.drawerBackdrop} role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><aside aria-label="Adicionar medicamento" aria-modal="true" className={styles.medicationDrawer} role="dialog">
    <header className={styles.drawerHeader}><div><span className={styles.panelKicker}>NOVA ROTINA</span><h2>Adicionar medicamento</h2><p>Os hor\u00e1rios ser\u00e3o calculados a partir da primeira dose.</p></div><button className={styles.drawerClose} type="button" aria-label="Fechar cadastro" onClick={onClose}>&times;</button></header>
    <div className={styles.drawerProgress}>{["Medicamento", "Agenda", "Detalhes", "Revisar"].map((label, index) => <span className={index <= step ? styles.drawerStepActive : ""} key={label}><i>{String(index + 1).padStart(2, "0")}</i>{label}</span>)}</div>
    <div className={styles.drawerBody}>
      {step === 0 ? <div className={styles.drawerFields}><label>Medicamento<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Ex.: Losartana" maxLength={120} /></label><label>Dosagem<input value={dosage} onChange={(event) => setDosage(event.target.value)} placeholder="Ex.: 50 mg" maxLength={80} /></label><p className={styles.fieldHint}>Informe apenas o que j\u00e1 foi orientado pelo seu m\u00e9dico ou farmac\u00eautico.</p></div> : null}
      {step === 1 ? <div className={styles.drawerFields}><label>Primeiro hor\u00e1rio<input type="time" value={firstDoseTime} onChange={(event) => setFirstDoseTime(event.target.value)} /></label><fieldset><legend>Frequ&ecirc;ncia</legend><div className={styles.choiceGrid}>{intervals.map((value) => <button className={value === intervalHours ? styles.choiceActive : styles.choice} key={value} type="button" onClick={() => setIntervalHours(value)}>A cada {value}h</button>)}</div></fieldset><p className={styles.fieldHint}>A agenda repete este intervalo ao longo do dia.</p></div> : null}
      {step === 2 ? <div className={styles.drawerFields}><fieldset><legend>Dura&ccedil;&atilde;o</legend><div className={styles.choiceGrid}><button className={durationDays === null ? styles.choiceActive : styles.choice} type="button" onClick={() => setDurationDays(null)}>Uso cont\u00ednuo</button><button className={durationDays !== null ? styles.choiceActive : styles.choice} type="button" onClick={() => setDurationDays(durationDays ?? 7)}>Por per\u00edodo</button></div></fieldset>{durationDays !== null ? <label>Quantidade de dias<input type="number" min={1} max={3650} value={durationDays} onChange={(event) => setDurationDays(Math.max(1, Math.min(3650, Number(event.target.value) || 1)))} /></label> : null}<label>Orienta&ccedil;&atilde;o (opcional)<textarea value={instructions} onChange={(event) => setInstructions(event.target.value)} maxLength={500} placeholder="Ex.: ap\u00f3s o almo\u00e7o, com \u00e1gua" /></label><fieldset><legend>Cor do medicamento</legend><div className={styles.colorGrid}>{colors.map((color) => <button className={colorToken === color.value ? styles.colorActive : styles.colorOption} type="button" key={color.value} onClick={() => setColorToken(color.value)}><i style={{ backgroundColor: color.swatch }} />{color.label}</button>)}</div></fieldset></div> : null}
      {step === 3 ? <div className={styles.reviewBlock}><span className={styles.panelKicker}>REVIS&Atilde;O</span><h3>{name}</h3><dl><div><dt>Dosagem</dt><dd>{dosage}</dd></div><div><dt>Primeira dose</dt><dd>{firstDoseTime}</dd></div><div><dt>Frequ&ecirc;ncia</dt><dd>A cada {intervalHours}h</dd></div><div><dt>Dura&ccedil;&atilde;o</dt><dd>{durationDays === null ? "Uso cont\u00ednuo" : `${durationDays} dias`}</dd></div><div><dt>Orienta&ccedil;&atilde;o</dt><dd>{instructions || "Nenhuma"}</dd></div></dl><p>Revise os dados antes de salvar. Voc\u00ea poder\u00e1 ajustar a rotina depois.</p></div> : null}
      {error ? <p className={styles.toolError} role="alert">{error}</p> : null}
    </div>
    <footer className={styles.drawerFooter}>{step > 0 ? <button className={styles.secondaryToolButton} type="button" onClick={() => { setError(""); setStep((value) => value - 1); }}>Voltar</button> : <span />}{step < 3 ? <button className={styles.primaryToolButton} type="button" onClick={next}>Continuar <span aria-hidden="true">&#8594;</span></button> : <button className={styles.primaryToolButton} type="button" disabled={saving} onClick={submit}>{saving ? "Salvando\u2026" : "Salvar medicamento"}</button>}</footer>
  </aside></div>;
}

function ChatPanel({ open, onClose, triggerRef }: { open: boolean; onClose: () => void; triggerRef: RefObject<HTMLButtonElement | null> }) {
  const router = useRouter(); const inputRef = useRef<HTMLInputElement>(null); const [sessionId, setSessionId] = useState<string | null>(null); const [messages, setMessages] = useState<WebChatMessage[]>([]); const [input, setInput] = useState(""); const [loading, setLoading] = useState(false); const [sending, setSending] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!open) return; let active = true; if (!sessionId) { setLoading(true); loadChatAction().then((result) => { if (!active) return; setSessionId(result.sessionId); setMessages(result.messages); }).catch(() => active && setError("N\u00e3o foi poss\u00edvel sincronizar a conversa agora.")).finally(() => active && setLoading(false)); } window.setTimeout(() => inputRef.current?.focus(), 180); return () => { active = false; }; }, [open, sessionId]);
  useEffect(() => { if (!open) return; const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") { onClose(); window.setTimeout(() => triggerRef.current?.focus(), 120); } }; document.addEventListener("keydown", onKey); return () => document.removeEventListener("keydown", onKey); }, [open, onClose, triggerRef]);
  async function send(value = input) { const content = value.trim(); if (!content || !sessionId || sending) return; setInput(""); setError(""); setSending(true); const optimistic = { id: `optimistic-${Date.now()}`, role: "user", content, created_at: new Date().toISOString(), metadata: {}, intent: null, session_id: sessionId, user_id: "" } as WebChatMessage; setMessages((current) => [...current, optimistic]); try { const result = await sendChatAction(sessionId, content); setMessages((current) => [...current.filter((message) => message.id !== optimistic.id), result.userMessage, result.assistantMessage]); if (result.dashboardChanged) router.refresh(); } catch (cause) { setMessages((current) => current.filter((message) => message.id !== optimistic.id)); setError(cause instanceof Error ? cause.message : "N\u00e3o foi poss\u00edvel enviar agora."); } finally { setSending(false); } }
  if (!open) return null;
  return <section aria-label="Assistente Vitalis" aria-modal="false" className={styles.chatPanel} role="dialog"><header className={styles.chatHeader}><span className={styles.chatMark}><CapsuleGlyph /></span><div><strong>Vitalis HUB</strong><span><i /> conectado \u00e0 sua rotina</span></div><button className={styles.chatClose} type="button" aria-label="Fechar assistente" onClick={onClose}><ChatGlyph close /></button></header><div className={styles.chatBody} aria-live="polite"><div className={styles.chatWelcome}><span className={styles.chatWelcomeOrb}><CapsuleGlyph /></span><div><strong>Ol\u00e1, eu sou o HUB.</strong><p>Posso consultar sua rotina, registrar uma toma ou cadastrar um medicamento.</p></div></div>{loading ? <p className={styles.chatLoading}>Sincronizando conversa\u2026</p> : null}{messages.map((message) => <div className={`${styles.chatMessage} ${message.role === "user" ? styles.chatMessageUser : styles.chatMessageAssistant} ${styles[`chatTone_${tone(message)}`]}`} key={message.id}><p>{message.content}</p><time>{new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit" }).format(new Date(message.created_at))}</time>{message.role === "assistant" && getSuggestions(message).length ? <div className={styles.chatSuggestions}>{getSuggestions(message).map((suggestion) => <button key={suggestion.prompt} type="button" disabled={sending} onClick={() => void send(suggestion.prompt)}>{suggestion.label ?? suggestion.prompt}</button>)}</div> : null}</div>)}{sending ? <div className={styles.chatTyping}><i /><i /><i /> Consultando sua rotina\u2026</div> : null}{error ? <p className={styles.toolError} role="alert">{error}</p> : null}</div><div className={styles.chatQuickPrompts}>{quickPrompts.map((prompt) => <button key={prompt} type="button" disabled={sending || loading} onClick={() => void send(prompt)}>{prompt}</button>)}</div><form className={styles.chatComposer} onSubmit={(event) => { event.preventDefault(); void send(); }}><input ref={inputRef} value={input} onChange={(event) => setInput(event.target.value)} placeholder="Digite uma mensagem\u2026" aria-label="Mensagem para o Vitalis HUB" maxLength={4000} /><button aria-label="Enviar mensagem" disabled={!input.trim() || sending || loading} type="submit">&#8593;</button></form></section>;
}

export function HubTools() {
  const [chatOpen, setChatOpen] = useState(false); const [medicationOpen, setMedicationOpen] = useState(false); const buttonRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { const onAdd = () => setMedicationOpen(true); window.addEventListener("vitalis:add-medication", onAdd); return () => window.removeEventListener("vitalis:add-medication", onAdd); }, []);
  return <><div className={styles.dashboardTools}><ChatPanel open={chatOpen} onClose={() => setChatOpen(false)} triggerRef={buttonRef} /><button ref={buttonRef} aria-expanded={chatOpen} aria-label={chatOpen ? "Fechar assistente Vitalis" : "Abrir assistente Vitalis"} className={`${styles.chatFab} ${chatOpen ? styles.chatFabOpen : ""}`} type="button" onClick={() => setChatOpen((value) => !value)}>{chatOpen ? <ChatGlyph close /> : <CapsuleGlyph />}</button></div><MedicationDrawer open={medicationOpen} onClose={() => setMedicationOpen(false)} /></>;
}